---
title: "Week 2 Discussion"
format: html
author: Liz Peterson
editor_options: 
  chunk_output_type: console
---

```{r}
library(here)
library(tidyverse)
library(sf)
library(tmap)
```

```{r}
col <- st_read(here('data','Colombia','Colombia.shp'))
roads <- st_read(here('data','RDLINE_colombia','RDLINE_colombia.shp'))
obs <- read_csv(here('data','dataves.csv'))
```

```{r}
obs <- read_csv(here('data','dataves.csv')) %>%
  as_tibble() %>%
  rename(long = decimal_longitude) %>%
  rename(lat = decimal_latitude)

obs <- obs %>%
  st_as_sf(coords = c("long","lat"), crs = 4326)
```

```{r}
unique(st_geometry_type(col))
# this can show us what kind of data these are
```

```{r}
col_andean <- col %>%
  mutate(N1_MacroBi = as.factor(N1_MacroBi)) %>%
  filter(N1_MacroBi == "Andean")
```

```{r}
tm_shape(col_andean) +
  tm_polygons() +
  tm_layout(main.title = "Andean Region of Colombia")
```

```{r}
st_crs(col)$units
```

```{r}
st_crs(col) == st_crs(obs)
```

```{r}
aves <- st_transform(obs, crs = st_crs(col))
```

```{r}
st_crs(col) == st_crs(aves)
```

